In [1]:
import numpy as np
from numpy.linalg import norm
import matplotlib.pyplot as plt

## Vectors

$$ A, B = point \\
 AB = \begin{bmatrix} b_1-a_1 & b_2-a_2 & b_3-a_3 & ... & b_n-a_n \end{bmatrix} \\
 a = Vector(dir, size, slope) \\
 \vec{a} = \begin{bmatrix} x_1 & x_2 & x_3 & ... & x_n \end{bmatrix} \\ 
 $$

In [2]:
# Vec creation 
x1, x2, x3 = 1.5, 2, 1
a = np.array([x1, x2, x3])
print(a)

[1.5 2.  1. ]


$$
\vec{a}\pm k = \begin{bmatrix} k\pm x_1 & k\pm x_2 & k\pm x_3 & ... & k\pm x_n \end{bmatrix} \\ 
\vec{a}k = \begin{bmatrix} kx_1 & kx_2 & kx_3 & ... & kx_n \end{bmatrix} \\ 
\vec{a} \ || \ \vec{b} :  \vec{a} = k\vec{b}
$$

In [2]:
a = np.array([2, 3, 5])
b = np.array([1, 2, 3])

In [22]:
k = 2
print('org vector: ', a)
print('scaler +- vector: ', a-k)
print('scaler to vector: ', a*k)

org vector:  [2 3 5]
scaler +- vector:  [0 1 3]
scaler to vector:  [ 4  6 10]


$$
L2: |\vec{a}| = \sqrt{x_1^2+x_2^2+x_3^2+...+x_n^2} \\
L1: |\vec{a}| = {|x_1|+|x_2|+|x_3|+...+|x_n|}
$$

In [23]:
# Norm Func
def vecNorm(a, norm=2):
    if norm==1:
        return np.sum(np.abs(a)) # L1Norm
    else:
        return np.sum(np.square(a)) # L2Norm

na = vecNorm(a)
# use numpy 
norm_a = np.linalg.norm(a)
print('norm of vector: ', norm_a)

norm of vector:  6.164414002968976


$$
unit \vec{V} : |\vec{V}| = 1 \\
Normalize \ \ e_\vec{V} : \frac{\vec{V}}{|\vec{V}|} \\
$$

In [24]:
def isUnitVec(a):
    return True if vecNorm(a) ==1 else False

def normalize(a):
    # convert2UnitVector
    return a / norm(a)

de

print('is vector unit? ', isUnitVec(a))
e_a = normalize(a)
print('is vector unit? ', isUnitVec(e_a))
print('united of vector: ', e_a)

is vector unit?  False
is vector unit?  True
united of vector:  [0.32444284 0.48666426 0.81110711]


$$
\vec{a} . \vec{b} : |\vec{a}| \ |\vec{b}| \ \cos{\theta} \\
\\ \vec{a} . \vec{b} : \sum_{i=0}^{n} a_i * b_i \\
\vec{a} . \vec{b} = 0 : \cos{\theta} = 0 \ \& \ \vec{a} \bot \vec{b}
$$

In [25]:
def dotProduct(a, b):
    sum_ = 0
    for i in range(len(a)):
        sum_ += a[i] * b[i]
    return sum_

ab = dotProduct(a, b)
# use numpy
ab = np.dot(a, b)
print('a.b:', ab)

a.b: 23


$$
\vec{b} . \vec{a} = \vec{a} . \vec{b} \\
\vec{a} . \vec{a} : |\vec{a}|^2 \\
\cos{\theta} = \frac{\vec{a} . \vec{b}}{|\vec{a}||\vec{a}|} \\
0 \leq \cos{\theta} \leq 1
$$

In [26]:
print('a.b:', np.dot(a, b))
print('b.a:', np.dot(b, a))

print(np.dot(a, a) , np.square(norm(a)))

# cos between tow vectors
def cosine_sim(a, b):
    # max sim is 1 bot is 0
    return np.dot(a, b) / (norm(a) * norm(a))

print(cosine_sim(a, b))

a.b: 23
b.a: 23
38 37.99999999999999
0.605263157894737


In [30]:
cosine_sim(b, b), cosine_sim([1, 0], [0, 1])

(1.0, 0.0)

$$
(X,Y,Z) \ Unit \ \ \ e_x = i: \begin{bmatrix} 1 & 0 & 0 \end{bmatrix} \ \ \
e_y = j: \begin{bmatrix} 0 & 1 & 0 \end{bmatrix} \ \ \
e_z = k: \begin{bmatrix} 0 & 0 & 1 \end{bmatrix} \\
\cos{\alpha} : \frac{X_a}{|\vec{a}|} ,\ \ \ \cos{\beta} : \frac{Y_a}{|\vec{a}|} ,\ \ \ \cos{\gamma} : \frac{Z_a}{|\vec{a}|}\\
e_a = (\cos\theta, \cos\beta, \cos\gamma) \\
e_a = 0 \leq a_i \leq 1
$$

In [52]:
i = np.array([1, 0, 0])
j = np.array([0, 1, 0])
k = np.array([0, 0, 1])

# some vector
a = np.array([3, 4, 2.5])
norm_a = norm(a, 2)
print('cosin2X {}, cosin2Y {}, cosin2Z {}'.format(*normalize(a)))

cosin2X 0.5366563145999494, cosin2Y 0.7155417527999327, cosin2Z 0.4472135954999579


$$
shadow \ \vec{a}\ on \ \vec{b} : \vec{a'}= \frac{a.b}{|\vec{b}|^2}\vec{b} \\
symmetric \ \vec{a}\ on \ \vec{b} : \vec{a''} = 2\vec{a'} - \vec{a} \\
|\vec{a}| = |\vec{a''}|
$$

In [70]:
def shadowAonB(a, b):
    norm_of_shadow = np.dot(a, b) / norm(b)
    eb = b / norm(b)
    # denormalize we need eV and norm of V
    # V = |V|e_V
    return norm_of_shadow * eb

shadow = shadowAonB(a, b)
print('shadow a on b: ', shadow)

def symmetricAonB(a, b):
    return 2*shadowAonB(a, b) - a

sym = symmetricAonB(a, b)
print('symmetric a on b: ', sym)

norm(sym) == norm(a)

shadow a on b:  [1.32142857 2.64285714 3.96428571]
symmetric a on b:  [-0.35714286  1.28571429  5.42857143]


True

$$
cross \ product \ \vec{c} = \vec{a} \times \vec{b} \\
\vec{c} \bot \vec{a}, \vec{b} \\
\vec{a} \times \vec{b} \neq \& \triangle \vec{b} \times \vec{a} \\
\vec{a} \times \vec{b} = \det\begin{bmatrix} a_1 & a_2 & a_3 \\ b_1 & b_2 & b_3 \end{bmatrix} 
= [(a_2 b_3 - a_3 b_2), -(a_1 b_3 - a_3 b_1), (a_1 b_2 - a_2 b_1)] \\
\vec{a} \times \vec{a} = \vec{0} \\
 \vec{a} \times \vec{b} = \vec{0} \leftrightarrow \vec{a} \parallel \vec{b}
$$

In [35]:
ab = np.cross(a, b)
ba = np.cross(b, a)
aa = np.cross(a, a)
print('a*b: ', ab)
print('b*a: ', ba)
print('a*a: ', aa)

print(np.dot(ab, a), cosine_sim(ba, a)) # a*b is _|_ on a & b
print(np.cross(a, a*2)) # a with any ka is ||

a*b:  [-1 -1  1]
b*a:  [ 1  1 -1]
a*a:  [0 0 0]
0 0.0
[0 0 0]


## Matrices

$$ B = \begin{bmatrix} 
b_{11} & b_{12} & \cdots & b_{1 n} \\  
b_{21} & b_{22} & \cdots & b_{2 n} \\  
\vdots & \vdots & \ddots & \vdots \\  
b_{m 1} & b_{m 2} & \cdots & b_{m n} \end{bmatrix}_{n\times m} \\
A = \begin{bmatrix} a_{ij} \end{bmatrix}_{n\times m} , a_{ij} = any \ Equation
$$

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.arange(1, 7).reshape(2, 3)

a.shape, b.shape

((2, 3), (2, 3))

$$
kA = \begin{bmatrix} ka_{ij} \end{bmatrix}_{n\times m}\\
A_{n\times m}\pm B_{p \times q} = \begin{bmatrix} a_{ij}\pm b_{ij} \end{bmatrix}_{n\times m \ or \ p\times q}
$$

In [3]:
np.add(a, b) # a+b

print(3*a)
print(a+b)

[[ 3  6  9]
 [12 15 18]]
[[ 2  4  6]
 [ 8 10 12]]


$$
A_{n\times m}\times B_{p \times q} = C_{n \times q} \ If \ m=p \\
A_{n\times m}\times B_{p \times q} \neq B_{n\times m}\times A_{p \times q} \ If \ Can \\ 
$$
$$
\begin{bmatrix} 
b_{11} & b_{12} & b_{1 n} \\  
b_{21} & b_{22} & b_{2 n} \\  
\vdots & \vdots & \vdots \\  
b_{31} & b_{32} & b_{3 n} \end{bmatrix}_{n\times 3} \times
\begin{bmatrix} 
a_{11} & a_{12} & \cdots & a_{1 n} \\  
a_{21} & a_{22} & \cdots & a_{2 n} \\    
a_{31} & a_{32} & \cdots & a_{3 n} \end{bmatrix}_{3\times m} = 
\begin{bmatrix} 
c_{11} & c_{12} & \cdots & c_{1 n} \\  
c_{21} & c_{22} & \cdots & c_{2 n} \\  
\vdots & \vdots & \ddots & \vdots \\  
c_{m 1} & c_{m 2} & \cdots & c_{m n} \end{bmatrix}_{n\times m} \\
$$
$$
c_{11} = \sum_{i,j=1}^{3} b_{1 j} \times a_{i 1}\ , \ c_{23} = \sum_{i,j=1}^{3} b_{2 j} \times a_{i 3} 
$$

In [4]:
a = np.array([[1, 2, 3],
              [3, 2, 1]])

b = np.array([[3, 2, 3], 
              [5, 2, 1], 
              [4, 1, 0]])
c = a@b
np.dot(a, b) # b@a not correct for shapes

array([[25,  9,  5],
       [23, 11, 11]])

In [5]:
def matmul(a, b):
    c = np.zeros(shape=(a.shape[0], b.shape[1]))
    for row in range(a.shape[0]):
        for col in range(b.shape[1]):
            c[row][col] = np.dot(a[row], b[:, col]) 
    return c       

matmul(a, b)

array([[25.,  9.,  5.],
       [23., 11., 11.]])

$$
A \times A = Can \ Be \ if \ A \ is \ Square \\
A \times A \times A \times \cdots \times A = A^n \\
A^{n-1} \times A = A \times A^{n-1} \\ 
$$

In [6]:
b@b # can compute b is square
(b@b)@b

array([[202,  99, 106],
       [230, 105, 102],
       [153,  67,  61]])

$$
Diagonal \ as \ D = \begin{bmatrix} 
a_{11} & 0 & \cdots & 0 \\  
0 & a_{22} & \cdots & 0 \\  
\vdots & \vdots & \ddots & 0 \\  
0 & 0 & 0 & a_{n, n} \end{bmatrix}_{n\times n}  \\
diag(D) = \begin{bmatrix} a_{11} & a_{22} & a_{11} & \cdots & a_{n n} \end{bmatrix} \\
scaler \ matrix \in D \rightarrow N = \begin{bmatrix} 
n & 0 & 0 \\  
0 & n & 0 \\  
0 & 0 & n \end{bmatrix}_{3\times 3}\\
$$
$$
kA = scaler\ k \times A
$$

In [7]:
c = np.diag(v=[1, 4, 3])
print(c)

scaler = np.eye(3)*2 # n=2
print(scaler)

c.diagonal(), scaler.diagonal() # get Diagonal of matrix 

[[1 0 0]
 [0 4 0]
 [0 0 3]]
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


(array([1, 4, 3]), array([2., 2., 2.]))

$$ I \in D \rightarrow I = \begin{bmatrix} 
1 & 0 & \cdots & 0 \\  
0 & 1 & \cdots & 0 \\  
\vdots & \vdots & 1 & 0 \\  
0 & 0 & 0 & 1 \end{bmatrix}_{n\times n} \\
$$
$$
IA = A = AI \\
I^{n} = I \\
$$

In [8]:
i = np.eye(3)
print(i)

print(a@i)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 2. 3.]
 [3. 2. 1.]]
[[1 2 3]
 [3 2 1]]


$$
A = \begin{bmatrix} 
1 & 2 \\  
0 & 3 \end{bmatrix}_{n\times m} \rightarrow A^{T} = \begin{bmatrix} 1 & 0 \\ 2 & 3 \end{bmatrix}_{m\times n} \\
(A^{T})^{T} = A \\
D^T = D \\
(A\times B \times C)^T = C^T\times B^T \times A^T
$$

In [9]:
print(a.T.shape, a.shape)

print((a.T.T==a).all())
print((np.eye(2).T == np.eye(2)).all())
print(((a@b).T == b.T@a.T).all())

(3, 2) (2, 3)
True
True
True


In [10]:
def isSquare(a):
    return True if a.shape[0]==a.shape[1] else False 

def con2Sq(a): # and symmmetric
    return a.T@a

$$
Up\triangle \ = \begin{bmatrix} 
b_{11} & b_{12} & b_{13} \\  
0 & b_{22} & b_{23} \\    
0 & 0 & b_{33} \end{bmatrix}_{3\times 3} \\
$$
$$
Down\triangle = \begin{bmatrix} 
b_{11} & 0 & 0 \\  
b_{21} & b_{22} & 0 \\    
b_{31} & b_{32} & b_{33} \end{bmatrix}_{3\times 3} \\
Up^{T} = Donw \ , \ Donw^T = Up
$$

In [11]:
down = np.tri(3)
up = np.tri(3).T
print(down)
print(up)

np.tril(b) # convert to triu for Down
np.triu(b) # convert to triu for Upper

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]


array([[3, 2, 3],
       [0, 2, 1],
       [0, 0, 0]])

$$
if \ A^T = A : Symmetric \ Matrix \ as \ S \\
D \in S , S \in Square \\
S = \begin{bmatrix} s_{11} & s' & s'' \\  s' & s_{22} & s''' \\  s'' & s''' & s_{33} \end{bmatrix}_{3\times 3} \\
$$
$$
A^T \times A \in S \\ A \times A^T \in S \\ A^T + A \in S \\
S' \pm S'' \in S
$$

In [12]:
def isSymm(a):
    if isSquare(a):
        return np.all(a==a.T)
    else: return False
    
def symmetrize(a):
    # a+a.T - main diag
    assert isSquare(a)
    return a + a.T - np.diag(a.diagonal())

if isSymm(b)==False: 
    print(symmetrize(b))

[[3 7 7]
 [7 2 2]
 [7 2 0]]


$$
if \ A^T = -A : AntiSymmetric \ Matrix \ as \  AS \\
AS = \begin{bmatrix} 0 & s' & s'' \\  -s' & 0 & s''' \\  -s'' & -s''' & 0 \end{bmatrix}_{3\times 3} \\
$$
$$
 A^T - A \in AS \\
 AS' \pm AS'' \in AS \\ kAS \in AS
$$

In [13]:
def isAntiSymm(a):
    assert isSquare(a)
    return np.all(-a==a.T)

def antiSymmetrize(a):
    # a+a.T - main diag
    assert isSquare(a)
    return a - a.T 

isAntiSymm(antiSymmetrize(b))

True

$$
det(A) = \begin{bmatrix} 
a & b \\  
c & d \end{bmatrix}_{2\times 2} \rightarrow |A| = (ad-cb) \\
|AB| = |A||B| \\
$$
$$
A = \begin{bmatrix} a & b & c \\  d & e & f \\  x & y & z \end{bmatrix}_{3\times 3} \rightarrow 
A_{del \ R1,C1}: Minor_{11} = \begin{bmatrix} e & f \\  y & z \end{bmatrix}_{2\times 2} \\
$$
$$
A_{ij} = (-1)^{i+j}|M_{ij}| : A_{23} = -1^5 \times \begin{vmatrix} a & b \\  x & y \end{vmatrix} \\
A_{ij} \neq a_{ij}
$$

In [14]:
from numpy.linalg import det

d = np.array([[1, 2],
              [3, 4]])
print('%.5f'%det(d))


def minor(a, i=0, j=0):
    return np.delete(np.delete(a,i,axis=0), j, axis=1)

def compatibility(a, i=0, j=0):#A_ij
    return -1**(i+j) * det(minor(a, i, j))

print(minor(b, 0, 0))
print(compatibility(b, 0, 0))

-2.00000
[[2 1]
 [1 0]]
1.0


$$
A = \begin{bmatrix} 1 & 2 & 1 \\  3 & 1 & 2 \\  0 & 2 & 3 \end{bmatrix}_{3\times 3} |A| \rightarrow^{Row 2} = a_{21}\times A_{21} + a_{22}\times A_{22} + a_{23} \times A_{23}\\
$$
$$
|A|\rightarrow^{Col 1} = 1\times \begin{vmatrix} 1 & 2 \\ 2 & 3 \end{vmatrix} - 3 \times \begin{bmatrix} 2 & 1 \\  2 & 3\end{bmatrix} = 1\times(3-4) - 3 \times (6-2) = -13 \\
$$
$$
det(D, Up\triangle, Down\triangle) = \prod_{i=0}^{n} diag_{i} \\
det(A) = det(A^T)
$$

In [15]:
a = np.array([[1, 2, 1],
              [3, 1, 2],
              [0, 2, 3]])

print(det(a))

up = np.triu(a)
print(up)
i = np.eye(3)
det(i), det(up)

-13.0
[[1 2 1]
 [0 1 2]
 [0 0 3]]


(1.0, 3.0000000000000004)

$$
det(A) = \begin{vmatrix} a & b & c \\  d & e & f \\  x & y & z \end{vmatrix}_{3\times 3} = - \begin{vmatrix} x & y & x \\  d & e & f \\  a & b & c \end{vmatrix}_{3\times 3} = - \begin{vmatrix} c & b & a \\  f & e & d \\  z & y & x \end{vmatrix}_{3\times 3} \\
$$
$$
det(A) = \begin{vmatrix} ac & bc & c \\  d & e & f \\  x & y & z \end{vmatrix}_{3\times 3} =^{Factor}  c\times det(A') \ \begin{vmatrix} a & b & 1 \\  d & e & f \\  x & y & z \end{vmatrix}_{3\times 3} =^{\times} det(A'') \begin{vmatrix} a & b & 1 \\  d & e & f \\  cx & cy & cz \end{vmatrix}_{3\times 3}
$$
$$
|kA_{n \times n}| = k^{n}|A_{n \times n}|
$$

In [22]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[3, 2, 1],
              [2, 3, 1],
              [1, 3, 2]])

print(det(a), det(-1*b))


3*det(np.array([[1, 2, 1],
                [2, 5, 4],
                [3, 8, 7]]))

det(np.array([[3*3, 2*3, 1*3],
              [6, 5, 4],
              [9, 8, 7]]))

0.0 -6.000000000000001


0.0

$$
\begin{vmatrix} a & b \\ c & d \end{vmatrix} = \begin{vmatrix} a & b\pm ka \\ c & d\pm kc \end{vmatrix} \\
A_{i} = kA_{any \ i} \ OR \ \begin{vmatrix} a & b \\ ak & bk \end{vmatrix} = Det(0) \\
if \ A^T = -A\ , \ Rank(A)=kn+1 : Det(0) \\
$$
$$
\begin{bmatrix} a & 2a & 3a \\ b & c & 3b \\ c & c & c \end{bmatrix} \rightarrow \begin{bmatrix} a & 0 & 0 \\ a & c-2a & 0 \\ c & -c & -2c \end{bmatrix} = 2ac(2a-c)\\
col_1 \rightarrow^{-2} col_2 \ , \ col_1 \rightarrow^{-3} col_3 
$$

In [17]:
aa = np.array([[1, 2], 
               [1, 2]])
print(det(aa))

aa = np.array([[5, 5], 
               [1/2, 1/2]])
print(det(aa))

0.0
0.0


$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix} \rightarrow A^{-1}= \frac{1}{det(A)}
\begin{bmatrix} d & -b \\ -c & a \end{bmatrix}_{Adjoint}^{A^*}\\
A^{-1}A = I \\
|A|= 0 \not\in \ A^{-1}
$$

In [24]:
from numpy.linalg import inv
inv(b)@b

array([[ 1.00000000e+00,  2.49800181e-16,  1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00,  0.00000000e+00],
       [-2.22044605e-16, -2.22044605e-16,  1.00000000e+00]])